fetlife/rollout

Gemfile.lock
rollout.gemspec
spec/legacy_spec.rb
spec/rollout_spec.rb
spec/spec_helper.rb

This runs `bundle update` and removes the version lock on RSpec, updating to RSpec 3
This also converts the spec syntax to the `expect` syntax, and switches to mocking with RSpec to make use of `double`

Update to RSpec 3

---

lib/rollout.rb
spec/rollout_spec.rb

We use a rails API and often send feature flags to the client side one by one. With these methods, we can send a summary of the feature flags to the client side.
`Rollout#feature_states` will return a hash where the key is the feature name and the value is a boolean based on if it's active or not. You can optionally pass in the user to get the states for a specific user.
`Rollout#active_features` will return an array of feature names that are active. You can optionally pass in the user to get the active features for that user.
Specs are written for each methods.

Add methods to get feature states and active features

---

lib/rollout.rb

`Rollout#inactive?` currently calls `Rollout#active` instead of `Rollout#active?`.

Fix typo in Rollout#inactive?

---

lib/rollout.rb
spec/rollout_spec.rb

Adds method to determine if user has been explicitly activated, as
opposed to via a percentage or group

Expose how user is active

---

lib/rollout.rb
spec/rollout_spec.rb

* add support for float percentages, eg: `$rollout.activate_percentage(:chat, 0.001)`

Allow percentage to be float with three decimal points

---

lib/rollout.rb
spec/rollout_spec.rb

That was confusing that I could add features using string, but couldn't remove them the same way:
```ruby
$rollout.activate_user('chat', user) # works fine
$rollout.delete('chat') # does not work
```

Add ability to delete feature using string feature name

---

README.md
lib/rollout.rb
spec/rollout_spec.rb

Adds data to serialized feature string as JSON
`percentage|user_id,user_id,...|group,_group...|data_json`
This data attribute is specific to each individual feature as opposed to
`options` which are the same for all features.

Allows miscellaneous data to be saved on individual features

---

lib/rollout.rb
spec/rollout_spec.rb

PR to address https://github.com/fetlife/rollout/issues/103
This PR makes using sets optional:
`Rollout.new(Redis.new, use_sets: true)` will use the old behavior with sets
`Rollout.new(Redis.new)` will use the "new" behavior with arrays. This would be the new default. If you prefer to use `set` as default, I can open a new PR and make the "new" behavior optional.
```
require 'redis'
rollout_client = Rollout.new(Redis.new)
iterations = 100
rollout_client.activate(:test_feature)
raw_users = []
100_000.times {|num| raw_users << num }
rollout_client_sets = Rollout.new(Redis.new, use_sets: true)
rollout_client_sets.activate_users(:test_feature, raw_users)
Benchmark.bm do |bm|
bm.report do
iterations.times do
rollout_client.active?(:test_feature, '123')
end
end
bm.report do
iterations.times do …
```

make using sets for users and groups optional

---

lib/rollout.rb
spec/rollout_spec.rb

This allows a user to pull out an array of features in a single call.

Introduce #multi_get

---

README.md

All the other examples use $rollout. I've have changed to use the same variable name like the rest of the examples.

Fix: update variable name in example.

---

.travis.yml
lib/rollout.rb

Adds the following:
- Support for Ruby 2.4.x
- Fix deprecation warnings for Ruby 2.4.x (`Fixnum` is deprecated and unified into `Integer`).
This fix is backwards compatible since `is_a?(Integer)` and `is_a?(Fixnum)` both return true on earlier Ruby versions.

Test against Ruby 2.4 + Fix deprecation warning

---

lib/rollout/version.rb
rollout.gemspec

Noticed this was missing while auditing gems this morning. Also bumped the patch version so that this change gets picked up in RubyGems

Add license to gemspec

---

lib/rollout.rb

Improve randomness uniformity

---

README.md

The given algorithm on documentation doesn't work to determine user shard on percentage
```
require 'redis'
require 'rollout'
rollout = Rollout.new(Redis.new, randomize_percentage: true)
class TestUser < Struct.new(:id)
end
feature_name = :test_feature
percentage = 50
rollout.activate_percentage(feature_name, percentage)
puts "id - rollout - algorithm"
('a'..'z').each do |id|
user = TestUser.new(id)
puts [ id, rollout.active?(feature_name, user), Zlib.crc32("#{id}#{feature_name}") % 100_000 < percentage * 1_000 ].join(' - ')
end
```
Will give you:
```
id - rollout - algorithm
a - true  - true
b - false - true
c - true  - false
d - true  - false
e - false - false
f - true  - true
g - false - false
h - false - false
i - true  - false
j - false - true
k - true  - true
l - true  - false
m - …
```

Fixed documentation for percentage algorithm

---

README.md

It wasn't obvious to us how the groups worked until we read the code.

Add note about defining groups during app startup

---

lib/rollout.rb

Currently when we calculate `feature_states` or `active_features` we perform N + 1 queries to Redis
This PR uses the `multi_get` method for these methods so that we only query Redis twice.

use multiget to build feature states and active features

---

lib/rollout.rb
spec/rollout_spec.rb

In the latest build 2.4.4 we have #143 merged and start using `multi_get` in `feature_states` and `active_features` but it will raise error when it's called with empty features (that's pretty common when we are running rspec on a test database)
```
Failure/Error: $rollout.feature_states(user)
Redis::CommandError:
ERR wrong number of arguments for 'mget' command
```

Fix crash on multi_get when calling with empty features

---

README.md

Add link to new minimalist rollout admin UI for managing your features.
https://github.com/fetlife/rollout-ui
It's very lightweight and you can set it up in seconds by mounting it as rack app into your Rails app.

Add link to Rollout UI

---

lib/rollout.rb
lib/rollout/feature.rb
spec/rollout/feature_spec.rb
spec/rollout_spec.rb

This changes signature of `Rollout::Feature#active?` to not require
`rollout` instance as first argument.
When querying same feature for different users, it was required to do
something like:
```ruby
feature = $rollout.get(:foo)
users.each do |user|
puts feature.active?($rollout, user)
end
```
This PR changes API so it's possible to just do:
```ruby
feature = $rollout.get(:foo)
users.each do |user|
puts feature.active?(user)
end
```
----
Note: This API was never advertised but just to be sure, we just bump
major version when releasing this change.

Improve Ergonomics of Rollout::Feature#active?

---

README.md

I don't currently have Rollout UI available, so I wanted a console-based way of inspecting the current state of a Rollout feature.
I discovered `get` in Rollout UI:
https://github.com/fetlife/rollout-ui/blob/485b635f69bed32a7b08afaaba65ce9b0d42cdf3/lib/rollout/ui/web.rb#L39-L40
This PR documents `get` so others may benefit.

Document $rollout.get
